packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - 'esbuild'

minimumReleaseAge: 10080
minimumReleaseAgeStrict: false
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.2'
  - '@tanstack/react-query@5.101.2'
  - '@types/three@0.185.0'
  - framer-motion@12.42.0
  - motion-dom@12.42.0
  - motion@12.42.0
  - three@0.185.0
