import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generateTheme, modeToVars } from '../src/utils/generate-theme';
import type { ThemeMode } from '../src/utils/theme-config';
import { CONFIGS } from '../src/utils/theme-config';

/* ---------- Compute all themes ---------- */

const themes = Object.fromEntries(
  Object.entries(CONFIGS).map(([name, config]) => [name, generateTheme(config)]),
) as Record<string, { dark: ThemeMode; light: ThemeMode }>;

/* ---------- Serialization helpers ---------- */

function q(s: string) {
  return `'${s}'`;
}

function serializeThemeMode(mode: ThemeMode, indent: number): string {
  const pad = ' '.repeat(indent);
  const pad2 = ' '.repeat(indent + 2);
  const groups: string[] = [];

  for (const [key, val] of Object.entries(mode)) {
    if (typeof val === 'string') {
      groups.push(`${pad}${key}: ${q(val)},`);
    } else {
      const fields = Object.entries(val as Record<string, string>)
        .map(([k, v]) => `${pad2}${k}: ${q(v)},`)
        .join('\n');
      groups.push(`${pad}${key}: {\n${fields}\n${pad}},`);
    }
  }

  return groups.join('\n');
}

function serializeVars(mode: ThemeMode, indent: number): string {
  const pad = ' '.repeat(indent);
  const vars = modeToVars(mode);
  return Object.entries(vars)
    .map(([key, value]) => `${pad}${key}: ${q(value)},`)
    .join('\n');
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function themeExportName(palette: string, mode: string) {
  if (palette === 'default' && mode === 'dark') return null;
  if (palette === 'default') return `default${capitalize(mode)}`;
  return `${palette}${capitalize(mode)}`;
}

/* ---------- Build output ---------- */

const paletteNames = Object.keys(themes);

const themeDataBlock = paletteNames
  .map(name => {
    const { dark, light } = themes[name];
    return `  ${name}: {
    dark: {
${serializeThemeMode(dark, 6)}
    },
    light: {
${serializeThemeMode(light, 6)}
    },
  }`;
  })
  .join(',\n');

const variants = paletteNames.flatMap(palette =>
  (['dark', 'light'] as const).map(mode => ({
    palette,
    mode,
    exportName: themeExportName(palette, mode),
    data: themes[palette][mode],
  })),
);

const createThemeBlocks = variants
  .filter(v => v.exportName !== null)
  .map(
    v =>
      `export const ${v.exportName} = stylex.createTheme(colors, {\n${serializeVars(v.data, 2)}\n});`,
  )
  .join('\n\n');

const themeMapEntries = variants
  .map(v => {
    const key = `${v.palette}-${v.mode}`;
    return `  '${key}': ${v.exportName ?? 'null'},`;
  })
  .join('\n');

const bgEntries = variants
  .map(
    v => `  '${v.palette}-${v.mode}': \`oklch(\${THEME.${v.palette}.${v.mode}.background.base})\`,`,
  )
  .join('\n');

const output = `// @generated by packages/ui/scripts/generate-themes.ts
// To regenerate: pnpm generate:themes
import * as stylex from '@stylexjs/stylex';

import type { Schemes } from '../utils/theme-config';

/* ---------- Theme data ---------- */

export const THEME = {
${themeDataBlock},
} satisfies Record<string, Schemes>;

/* ---------- Derived types ---------- */

export type Palette = keyof typeof THEME;
export type ColorScheme = keyof Schemes;
export type ThemeKey = \`\${Palette}-\${ColorScheme}\`;

export const PALETTES = Object.keys(THEME) as Palette[];
export const COLOR_SCHEMES = Object.keys(THEME[PALETTES[0]]) as ColorScheme[];

/* ---------- StyleX tokens ---------- */

export const colors = stylex.defineVars({
${serializeVars(themes[paletteNames[0]].dark, 2)}
});

${createThemeBlocks}

/* ---------- Theme switching ---------- */

export const themeMap: Record<ThemeKey, typeof defaultLight | null> = {
${themeMapEntries}
};

export const themeBackgrounds: Record<ThemeKey, string> = {
${bgEntries}
};
`;

const outPath = resolve(import.meta.dirname, '..', 'src', 'tokens', 'themes.stylex.ts');
writeFileSync(outPath, output);
console.log('Generated', outPath);
